name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        stack build
    - name: Deploy
      # We should only deploy when pushed to master
      # so we will probably need a seperate workflow
      # for pushes and pull_requests respectively
      run: |
        echo todo
